replicaCount: 1

image:
  repository: registry.gitlab.unige.ch/pereira_oct/docker-project/currencyservice
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 7000

env:
  - name: PORT
    value: "7000"
  - name: DISABLE_PROFILER
    value: "1"