apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  PORT: {{ .Values.service.port | quote }}
  CART_SERVICE_ADDR: {{ .Values.config.cartServiceAddr | quote }}
  CURRENCY_SERVICE_ADDR: {{ .Values.config.currencyServiceAddr | quote }}
  EMAIL_SERVICE_ADDR: {{ .Values.config.emailServiceAddr | quote }}
  PAYMENT_SERVICE_ADDR: {{ .Values.config.paymentServiceAddr | quote }}
  SHIPPING_SERVICE_ADDR: {{ .Values.config.shippingServiceAddr | quote }}
  PRODUCT_CATALOG_SERVICE_ADDR: {{ .Values.config.productCatalogServiceAddr | quote }}